// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/ustackq/indagate/api/v1/models"
)

// NewPostConfigParams creates a new PostConfigParams object
// no default values defined in spec.
func NewPostConfigParams() PostConfigParams {

	return PostConfigParams{}
}

// PostConfigParams contains all the bound params for the post config operation
// typically these are obtained from a http.Request
//
// swagger:parameters postConfig
type PostConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The config to create
	  Required: true
	  In: body
	*/
	Config *models.IndagateConfig
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigParams() beforehand.
func (o *PostConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.IndagateConfig
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("config", "body"))
			} else {
				res = append(res, errors.NewParseError("config", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Config = &body
			}
		}
	} else {
		res = append(res, errors.Required("config", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
