// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostConfigHandlerFunc turns a function with the right signature into a post config handler
type PostConfigHandlerFunc func(PostConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigHandlerFunc) Handle(params PostConfigParams) middleware.Responder {
	return fn(params)
}

// PostConfigHandler interface for that can handle valid post config params
type PostConfigHandler interface {
	Handle(PostConfigParams) middleware.Responder
}

// NewPostConfig creates a new http.Handler for the post config operation
func NewPostConfig(ctx *middleware.Context, handler PostConfigHandler) *PostConfig {
	return &PostConfig{Context: ctx, Handler: handler}
}

/*PostConfig swagger:route POST /install general postConfig

Post a new config or update an existing one

*/
type PostConfig struct {
	Context *middleware.Context
	Handler PostConfigHandler
}

func (o *PostConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
