// Code generated by go-swagger; DO NOT EDIT.

package silence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// PostConfigHandlerFunc turns a function with the right signature into a post config handler
type PostConfigHandlerFunc func(PostConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigHandlerFunc) Handle(params PostConfigParams) middleware.Responder {
	return fn(params)
}

// PostConfigHandler interface for that can handle valid post config params
type PostConfigHandler interface {
	Handle(PostConfigParams) middleware.Responder
}

// NewPostConfig creates a new http.Handler for the post config operation
func NewPostConfig(ctx *middleware.Context, handler PostConfigHandler) *PostConfig {
	return &PostConfig{Context: ctx, Handler: handler}
}

/*PostConfig swagger:route POST /install silence postConfig

Post a new config or update an existing one

*/
type PostConfig struct {
	Context *middleware.Context
	Handler PostConfigHandler
}

func (o *PostConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostConfigOKBody post config o k body
// swagger:model PostConfigOKBody
type PostConfigOKBody struct {

	// silence ID
	SilenceID string `json:"silenceID,omitempty"`
}

// Validate validates this post config o k body
func (o *PostConfigOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostConfigOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostConfigOKBody) UnmarshalBinary(b []byte) error {
	var res PostConfigOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
